services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tracktime
      POSTGRES_DB: tracktime_db
    ports:
      - "5432:5432"