# Actuator
management.endpoint.health.show-details=always

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:4173

# Logging
logging.structured.format.console=

# OpenAPI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs

# Scalar
scalar.enabled=true
scalar.path=/scalar